# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.package_item import PackageItem

class TestPackageItem(unittest.TestCase):
    """PackageItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PackageItem:
        """Test PackageItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PackageItem`
        """
        model = PackageItem()
        if include_optional:
            return PackageItem(
                asset_id = 12345,
                instrumentation_part_code = 'PVG',
                instrumentation_part_name = 'Piano/Vocal/Guitar',
                count = 1,
                sequence = 1,
                score = True
            )
        else:
            return PackageItem(
        )
        """

    def testPackageItem(self):
        """Test PackageItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
