# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hlconnect_client.api.purchase_cancel_api import PurchaseCancelApi


class TestPurchaseCancelApi(unittest.TestCase):
    """PurchaseCancelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchaseCancelApi()

    def tearDown(self) -> None:
        pass

    def test_connector_purchase_cancel(self) -> None:
        """Test case for connector_purchase_cancel

        Cancel purchase order line item
        """
        pass


if __name__ == '__main__':
    unittest.main()
