# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hlconnect_client.models.order_item import OrderItem

class TestOrderItem(unittest.TestCase):
    """OrderItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderItem:
        """Test OrderItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderItem`
        """
        model = OrderItem()
        if include_optional:
            return OrderItem(
                order_id = 1,
                order_line_id = 11,
                asset_id = 1499,
                customer = 'John Doe',
                unit_price = 3.99,
                line_item_price = 3.99,
                quantity = 1,
                country_code = 'DE',
                download_url = 'https://haldms.halleonard.com/nf/download/D2FE1583831F4047875D981C5DBFBA41',
                view_url = 'https://haldms.halleonard.com/nf/view/D2FE1583831F4047875D981C5DBFBA41',
                status = 'COMPLETED'
            )
        else:
            return OrderItem(
        )
        """

    def testOrderItem(self):
        """Test OrderItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
