# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.purchase_view_url_api import PurchaseViewUrlApi


class TestPurchaseViewUrlApi(unittest.TestCase):
    """PurchaseViewUrlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchaseViewUrlApi()

    def tearDown(self) -> None:
        pass

    def test_connector_purchase_view_url(self) -> None:
        """Test case for connector_purchase_view_url

        Get asset view URL
        """
        pass


if __name__ == '__main__':
    unittest.main()
