# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.purchase_register_request import PurchaseRegisterRequest

class TestPurchaseRegisterRequest(unittest.TestCase):
    """PurchaseRegisterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PurchaseRegisterRequest:
        """Test PurchaseRegisterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PurchaseRegisterRequest`
        """
        model = PurchaseRegisterRequest()
        if include_optional:
            return PurchaseRegisterRequest(
                asset_id = 4000,
                order_number = 12345,
                order_line_id = 1,
                country_code = 'US',
                line_item_price = 3.95,
                unit_price = 11.85,
                quantity = 3,
                customer = 'John Customer',
                parts = [
                    openapi_client.models.asset_part_form.AssetPartForm(
                        asset_id = 472169, 
                        order_line_id = 1, )
                    ]
            )
        else:
            return PurchaseRegisterRequest(
                asset_id = 4000,
                order_number = 12345,
                order_line_id = 1,
                country_code = 'US',
                line_item_price = 3.95,
                unit_price = 11.85,
                quantity = 3,
                customer = 'John Customer',
        )
        """

    def testPurchaseRegisterRequest(self):
        """Test PurchaseRegisterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
