# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hlconnect_client.models.purchase_validate_before_payment_request import PurchaseValidateBeforePaymentRequest

class TestPurchaseValidateBeforePaymentRequest(unittest.TestCase):
    """PurchaseValidateBeforePaymentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PurchaseValidateBeforePaymentRequest:
        """Test PurchaseValidateBeforePaymentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PurchaseValidateBeforePaymentRequest`
        """
        model = PurchaseValidateBeforePaymentRequest()
        if include_optional:
            return PurchaseValidateBeforePaymentRequest(
                asset_id = 123,
                customer_ip = '203.0.113.1',
                quantity = 1
            )
        else:
            return PurchaseValidateBeforePaymentRequest(
                asset_id = 123,
                customer_ip = '203.0.113.1',
                quantity = 1,
        )
        """

    def testPurchaseValidateBeforePaymentRequest(self):
        """Test PurchaseValidateBeforePaymentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
