# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.assets_list_response import AssetsListResponse

class TestAssetsListResponse(unittest.TestCase):
    """AssetsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetsListResponse:
        """Test AssetsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetsListResponse`
        """
        model = AssetsListResponse()
        if include_optional:
            return AssetsListResponse(
                assets = [
                    openapi_client.models.asset_item.AssetItem(
                        asset_id = 1080, 
                        format_short_name = 'PVG', 
                        format = 'Piano/Vocal/Guitar', 
                        page_count = 4, 
                        title = 'There's A Kind Of Hush (All Over The World)', 
                        description = 'I Will Bless the Lord is from a collection of Psalm-based songs composed by Paul K Heatley while participating in an artist residency program run by Fuller Seminary for which Paul was sponsored by his local church in Pasadena, CA. The words (and number) of Psalm 34 inspired a joyful tune in &#190; time, rendered here in a simple piano arrangement, which may be suitable for congregational worship (though it does feature a middle-eight and an instrumental verse since Paul tries to avoid the typical verse-chorus-verse-chorus format)', 
                        song_number = 66720, 
                        public_domain = True, 
                        external_ref = 'AME', 
                        external_ref_id = 681520, 
                        voicing = 'SATB', 
                        performance_time = 260, 
                        difficulty_level_low = 2, 
                        difficulty_level_high = 2, 
                        min_qty = 2, 
                        tempo = 92, 
                        world = True, 
                        retail_price = 2, 
                        smd_id = '0293482', 
                        asset_type = 'FOLIO', 
                        explicit = False, 
                        partable = True, 
                        countries = ["US","CA"], 
                        instruments = [
                            openapi_client.models.instrument_item.InstrumentItem(
                                type = 'STR', 
                                name = 'Strings', )
                            ], 
                        categories = ["Pop","Rock"], 
                        images = [
                            openapi_client.models.image_item.ImageItem(
                                name = 'Cover', 
                                url = '/images/covers/12345.jpg', )
                            ], 
                        contributors = [
                            openapi_client.models.contributor_item.ContributorItem(
                                is_primary = True, 
                                name = 'John Doe', 
                                mbid = '12345678-1234-1234-1234-123456789012', 
                                role = 'Composer', )
                            ], 
                        keywords = ["wedding","love"], 
                        related_goods = [
                            openapi_client.models.related_good_item.RelatedGoodItem(
                                related_product_id = 12345, 
                                group_type_id = 1, 
                                good_type = 'H', 
                                sheet = True, 
                                featured = False, 
                                prime_src = True, )
                            ], 
                        renderings = [
                            openapi_client.models.rendering_item.RenderingItem(
                                type = 'preview', 
                                usage = 'streaming', )
                            ], 
                        series = ["Best Sellers","Top Hits"], 
                        skills = ["Beginner","Intermediate"], 
                        usergens = [
                            openapi_client.models.usergen_item.UsergenItem(
                                black_box = False, 
                                arrangeable = True, 
                                vendor_product_type = 'DIGITAL', 
                                seller_id = 123, 
                                authorized_performers = 5, 
                                content_provider = 'Hal Leonard', 
                                adaptation_product_id = 456, 
                                adaptation_vendor = 'Sheet Music Plus', 
                                vendor_song_id = 'V12345', 
                                commission_override_rate = 0.15, 
                                publisher_name = 'HL Publications', 
                                medley_assets = [
                                    openapi_client.models.medley_asset_item.MedleyAssetItem(
                                        name = 'Song Title', 
                                        song_catalog_id = 'SC12345', 
                                        hl_song_id = 'HL12345', 
                                        sequence = 1, )
                                    ], )
                            ], 
                        prices = [
                            openapi_client.models.price_item.PriceItem(
                                type_id = 1, 
                                type_usage = 'digital', 
                                price = 2.99, )
                            ], 
                        packages = [
                            openapi_client.models.package_item.PackageItem(
                                asset_id = 12345, 
                                instrumentation_part_code = 'PVG', 
                                instrumentation_part_name = 'Piano/Vocal/Guitar', 
                                count = 1, 
                                sequence = 1, 
                                score = True, )
                            ], )
                    ],
                last_id = 472169,
                next_page = '/assets/list?page_size=20&last_id=472169'
            )
        else:
            return AssetsListResponse(
                assets = [
                    openapi_client.models.asset_item.AssetItem(
                        asset_id = 1080, 
                        format_short_name = 'PVG', 
                        format = 'Piano/Vocal/Guitar', 
                        page_count = 4, 
                        title = 'There's A Kind Of Hush (All Over The World)', 
                        description = 'I Will Bless the Lord is from a collection of Psalm-based songs composed by Paul K Heatley while participating in an artist residency program run by Fuller Seminary for which Paul was sponsored by his local church in Pasadena, CA. The words (and number) of Psalm 34 inspired a joyful tune in &#190; time, rendered here in a simple piano arrangement, which may be suitable for congregational worship (though it does feature a middle-eight and an instrumental verse since Paul tries to avoid the typical verse-chorus-verse-chorus format)', 
                        song_number = 66720, 
                        public_domain = True, 
                        external_ref = 'AME', 
                        external_ref_id = 681520, 
                        voicing = 'SATB', 
                        performance_time = 260, 
                        difficulty_level_low = 2, 
                        difficulty_level_high = 2, 
                        min_qty = 2, 
                        tempo = 92, 
                        world = True, 
                        retail_price = 2, 
                        smd_id = '0293482', 
                        asset_type = 'FOLIO', 
                        explicit = False, 
                        partable = True, 
                        countries = ["US","CA"], 
                        instruments = [
                            openapi_client.models.instrument_item.InstrumentItem(
                                type = 'STR', 
                                name = 'Strings', )
                            ], 
                        categories = ["Pop","Rock"], 
                        images = [
                            openapi_client.models.image_item.ImageItem(
                                name = 'Cover', 
                                url = '/images/covers/12345.jpg', )
                            ], 
                        contributors = [
                            openapi_client.models.contributor_item.ContributorItem(
                                is_primary = True, 
                                name = 'John Doe', 
                                mbid = '12345678-1234-1234-1234-123456789012', 
                                role = 'Composer', )
                            ], 
                        keywords = ["wedding","love"], 
                        related_goods = [
                            openapi_client.models.related_good_item.RelatedGoodItem(
                                related_product_id = 12345, 
                                group_type_id = 1, 
                                good_type = 'H', 
                                sheet = True, 
                                featured = False, 
                                prime_src = True, )
                            ], 
                        renderings = [
                            openapi_client.models.rendering_item.RenderingItem(
                                type = 'preview', 
                                usage = 'streaming', )
                            ], 
                        series = ["Best Sellers","Top Hits"], 
                        skills = ["Beginner","Intermediate"], 
                        usergens = [
                            openapi_client.models.usergen_item.UsergenItem(
                                black_box = False, 
                                arrangeable = True, 
                                vendor_product_type = 'DIGITAL', 
                                seller_id = 123, 
                                authorized_performers = 5, 
                                content_provider = 'Hal Leonard', 
                                adaptation_product_id = 456, 
                                adaptation_vendor = 'Sheet Music Plus', 
                                vendor_song_id = 'V12345', 
                                commission_override_rate = 0.15, 
                                publisher_name = 'HL Publications', 
                                medley_assets = [
                                    openapi_client.models.medley_asset_item.MedleyAssetItem(
                                        name = 'Song Title', 
                                        song_catalog_id = 'SC12345', 
                                        hl_song_id = 'HL12345', 
                                        sequence = 1, )
                                    ], )
                            ], 
                        prices = [
                            openapi_client.models.price_item.PriceItem(
                                type_id = 1, 
                                type_usage = 'digital', 
                                price = 2.99, )
                            ], 
                        packages = [
                            openapi_client.models.package_item.PackageItem(
                                asset_id = 12345, 
                                instrumentation_part_code = 'PVG', 
                                instrumentation_part_name = 'Piano/Vocal/Guitar', 
                                count = 1, 
                                sequence = 1, 
                                score = True, )
                            ], )
                    ],
                last_id = 472169,
                next_page = '/assets/list?page_size=20&last_id=472169',
        )
        """

    def testAssetsListResponse(self):
        """Test AssetsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
