# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hlconnect_client.models.purchase_in_processing_response import PurchaseInProcessingResponse

class TestPurchaseInProcessingResponse(unittest.TestCase):
    """PurchaseInProcessingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PurchaseInProcessingResponse:
        """Test PurchaseInProcessingResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PurchaseInProcessingResponse`
        """
        model = PurchaseInProcessingResponse()
        if include_optional:
            return PurchaseInProcessingResponse(
                status = 'PROCESSING'
            )
        else:
            return PurchaseInProcessingResponse(
        )
        """

    def testPurchaseInProcessingResponse(self):
        """Test PurchaseInProcessingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
