# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.view_url import ViewUrl

class TestViewUrl(unittest.TestCase):
    """ViewUrl unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ViewUrl:
        """Test ViewUrl
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ViewUrl`
        """
        model = ViewUrl()
        if include_optional:
            return ViewUrl(
                url = 'https://haldms.halleonard.com/nf/view/14656D8JKHK7J3209E27D4BA7AF87EC1'
            )
        else:
            return ViewUrl(
        )
        """

    def testViewUrl(self):
        """Test ViewUrl"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
