# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hlconnect_client.models.medley_asset_item import MedleyAssetItem

class TestMedleyAssetItem(unittest.TestCase):
    """MedleyAssetItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MedleyAssetItem:
        """Test MedleyAssetItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MedleyAssetItem`
        """
        model = MedleyAssetItem()
        if include_optional:
            return MedleyAssetItem(
                name = 'Song Title',
                song_catalog_id = 'SC12345',
                hl_song_id = 'HL12345',
                sequence = 1
            )
        else:
            return MedleyAssetItem(
        )
        """

    def testMedleyAssetItem(self):
        """Test MedleyAssetItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
