# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "hlconnect_client"
VERSION = "0.0.2"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="HL Connect",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "HL Connect"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Proprietary",
    long_description_content_type='text/markdown',
    long_description="""\
    HL Connect provides a simplified API interface to Hal Leonard&#39;s Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard&#39;s digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets
    """,  # noqa: E501
    package_data={"hlconnect_client": ["py.typed"]},
)