# coding: utf-8

# flake8: noqa
"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from hlconnect_client.models.asset_item import AssetItem
from hlconnect_client.models.asset_part_form import AssetPartForm
from hlconnect_client.models.assets_list_response import AssetsListResponse
from hlconnect_client.models.contributor_item import ContributorItem
from hlconnect_client.models.download_url import DownloadUrl
from hlconnect_client.models.error_response import ErrorResponse
from hlconnect_client.models.health_item import HealthItem
from hlconnect_client.models.image_item import ImageItem
from hlconnect_client.models.instrument_item import InstrumentItem
from hlconnect_client.models.medley_asset_item import MedleyAssetItem
from hlconnect_client.models.order_item import OrderItem
from hlconnect_client.models.order_processing_failed_response import OrderProcessingFailedResponse
from hlconnect_client.models.package_item import PackageItem
from hlconnect_client.models.price_item import PriceItem
from hlconnect_client.models.purchase_in_processing_response import PurchaseInProcessingResponse
from hlconnect_client.models.purchase_register_request import PurchaseRegisterRequest
from hlconnect_client.models.purchase_validate_before_payment_request import PurchaseValidateBeforePaymentRequest
from hlconnect_client.models.related_good_item import RelatedGoodItem
from hlconnect_client.models.rendering_item import RenderingItem
from hlconnect_client.models.usergen_item import UsergenItem
from hlconnect_client.models.validation_token import ValidationToken
from hlconnect_client.models.view_url import ViewUrl

