# coding: utf-8

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from hlconnect_client.models.asset_part_form import AssetPartForm
from typing import Optional, Set
from typing_extensions import Self

class PurchaseRegisterRequest(BaseModel):
    """
    Request payload for registering a new purchase transaction. Contains all required information to initiate the purchase of a digital asset.
    """ # noqa: E501
    token: StrictStr = Field(description="Validation token")
    order_number: StrictInt = Field(description="Vendor-generated order number that uniquely identifies this purchase order.")
    order_line_id: StrictInt = Field(description="Line number within the order that identifies this specific item. Used to distinguish multiple items in the same order.")
    line_item_price: Union[StrictFloat, StrictInt] = Field(description="Price for this specific line item as a real number. Represents the total price for the quantity specified.")
    unit_price: Union[StrictFloat, StrictInt] = Field(description="Unit price for a single item as a real number")
    customer: StrictStr = Field(description="Customer name for asset personalization. May be printed on the asset if personalization is supported.")
    parts: Optional[List[AssetPartForm]] = Field(default=None, description="Optional parts specification for ensemble assets. Allows customers to select specific parts of an ensemble for individual purchase rather than buying the complete set.")
    __properties: ClassVar[List[str]] = ["token", "order_number", "order_line_id", "line_item_price", "unit_price", "customer", "parts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PurchaseRegisterRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parts (list)
        _items = []
        if self.parts:
            for _item_parts in self.parts:
                if _item_parts:
                    _items.append(_item_parts.to_dict())
            _dict['parts'] = _items
        # set to None if parts (nullable) is None
        # and model_fields_set contains the field
        if self.parts is None and "parts" in self.model_fields_set:
            _dict['parts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PurchaseRegisterRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "token": obj.get("token"),
            "order_number": obj.get("order_number"),
            "order_line_id": obj.get("order_line_id"),
            "line_item_price": obj.get("line_item_price"),
            "unit_price": obj.get("unit_price"),
            "customer": obj.get("customer"),
            "parts": [AssetPartForm.from_dict(_item) for _item in obj["parts"]] if obj.get("parts") is not None else None
        })
        return _obj


