# coding: utf-8

# flake8: noqa
"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.asset_item import AssetItem
from openapi_client.models.asset_part_form import AssetPartForm
from openapi_client.models.assets_list_response import AssetsListResponse
from openapi_client.models.contributor_item import ContributorItem
from openapi_client.models.download_url import DownloadUrl
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.health_item import HealthItem
from openapi_client.models.image_item import ImageItem
from openapi_client.models.instrument_item import InstrumentItem
from openapi_client.models.medley_asset_item import MedleyAssetItem
from openapi_client.models.order_item import OrderItem
from openapi_client.models.order_processing_failed_response import OrderProcessingFailedResponse
from openapi_client.models.package_item import PackageItem
from openapi_client.models.price_item import PriceItem
from openapi_client.models.purchase_in_processing_response import PurchaseInProcessingResponse
from openapi_client.models.purchase_register_request import PurchaseRegisterRequest
from openapi_client.models.related_good_item import RelatedGoodItem
from openapi_client.models.rendering_item import RenderingItem
from openapi_client.models.usergen_item import UsergenItem
from openapi_client.models.view_url import ViewUrl

