# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MedleyAssetItem(BaseModel):
    """
    Medley asset information included in user-generated content.
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Medley asset name.")
    song_catalog_id: Optional[StrictStr] = Field(default=None, description="Song catalog ID.")
    hl_song_id: Optional[StrictStr] = Field(default=None, description="HL song ID.")
    sequence: Optional[StrictInt] = Field(default=None, description="Sequence number.")
    __properties: ClassVar[List[str]] = ["name", "song_catalog_id", "hl_song_id", "sequence"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MedleyAssetItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if song_catalog_id (nullable) is None
        # and model_fields_set contains the field
        if self.song_catalog_id is None and "song_catalog_id" in self.model_fields_set:
            _dict['song_catalog_id'] = None

        # set to None if hl_song_id (nullable) is None
        # and model_fields_set contains the field
        if self.hl_song_id is None and "hl_song_id" in self.model_fields_set:
            _dict['hl_song_id'] = None

        # set to None if sequence (nullable) is None
        # and model_fields_set contains the field
        if self.sequence is None and "sequence" in self.model_fields_set:
            _dict['sequence'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MedleyAssetItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "song_catalog_id": obj.get("song_catalog_id"),
            "hl_song_id": obj.get("hl_song_id"),
            "sequence": obj.get("sequence")
        })
        return _obj


