# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class OrderItem(BaseModel):
    """
    Represents a purchase order item with complete status and fulfillment information.
    """ # noqa: E501
    order_id: Optional[StrictInt] = Field(default=None, description="Vendor order ID that uniquely identifies this purchase order.")
    order_line_id: Optional[StrictInt] = Field(default=None, description="Line number within the order that identifies this specific item.")
    asset_id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the digital asset associated with this order item.")
    customer: Optional[StrictStr] = Field(default=None, description="Customer name associated with the order for personalization purposes.")
    unit_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unit price for a single item in the vendor's currency.")
    line_item_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total price for this line item (unit price × quantity) in the vendor's currency.")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Quantity of items ordered in this line item.")
    country_code: Optional[StrictStr] = Field(default=None, description="ISO 3166-1 alpha-2 country code for the country of sale.")
    download_url: Optional[StrictStr] = Field(default=None, description="Secure download URL for the purchased asset. Available when the order is completed. Null if not yet fulfilled or if not applicable.")
    view_url: Optional[StrictStr] = Field(default=None, description="Secure view URL for the purchased asset. Available when the order is completed. Null if not yet fulfilled or if not applicable.")
    status: Optional[StrictStr] = Field(default=None, description="Current status of the order item (e.g., COMPLETED, PROCESSING, FAILED).")
    __properties: ClassVar[List[str]] = ["order_id", "order_line_id", "asset_id", "customer", "unit_price", "line_item_price", "quantity", "country_code", "download_url", "view_url", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if download_url (nullable) is None
        # and model_fields_set contains the field
        if self.download_url is None and "download_url" in self.model_fields_set:
            _dict['download_url'] = None

        # set to None if view_url (nullable) is None
        # and model_fields_set contains the field
        if self.view_url is None and "view_url" in self.model_fields_set:
            _dict['view_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "order_id": obj.get("order_id"),
            "order_line_id": obj.get("order_line_id"),
            "asset_id": obj.get("asset_id"),
            "customer": obj.get("customer"),
            "unit_price": obj.get("unit_price"),
            "line_item_price": obj.get("line_item_price"),
            "quantity": obj.get("quantity"),
            "country_code": obj.get("country_code"),
            "download_url": obj.get("download_url"),
            "view_url": obj.get("view_url"),
            "status": obj.get("status")
        })
        return _obj


