# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RelatedGoodItem(BaseModel):
    """
    Related goods (physical products, digital bundles, etc.) associated with an asset.
    """ # noqa: E501
    related_product_id: Optional[StrictInt] = Field(default=None, description="Related product ID.")
    group_type_id: Optional[StrictInt] = Field(default=None, description="Group type ID.")
    good_type: Optional[StrictStr] = Field(default=None, description="Good type (H for hard goods, D for digital, V for virtual).")
    sheet: Optional[StrictBool] = Field(default=None, description="Sheet indicator.")
    featured: Optional[StrictBool] = Field(default=None, description="Featured indicator.")
    prime_src: Optional[StrictBool] = Field(default=None, description="Prime source indicator.")
    __properties: ClassVar[List[str]] = ["related_product_id", "group_type_id", "good_type", "sheet", "featured", "prime_src"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RelatedGoodItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RelatedGoodItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "related_product_id": obj.get("related_product_id"),
            "group_type_id": obj.get("group_type_id"),
            "good_type": obj.get("good_type"),
            "sheet": obj.get("sheet"),
            "featured": obj.get("featured"),
            "prime_src": obj.get("prime_src")
        })
        return _obj


