# coding: utf-8

"""
    HL Connector

    HL Connector provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.medley_asset_item import MedleyAssetItem
from typing import Optional, Set
from typing_extensions import Self

class UsergenItem(BaseModel):
    """
    User-generated content or customization options associated with an asset.
    """ # noqa: E501
    black_box: Optional[StrictBool] = Field(default=None, description="Black box flag indicating if the asset is a black box item.")
    arrangeable: Optional[StrictBool] = Field(default=None, description="Arrangeable flag indicating if the asset can be arranged.")
    vendor_product_type: Optional[StrictStr] = Field(default=None, description="Vendor product type identifier.")
    seller_id: Optional[StrictInt] = Field(default=None, description="Seller ID for the user-generated content.")
    authorized_performers: Optional[StrictInt] = Field(default=None, description="Number of authorized performers for the content.")
    content_provider: Optional[StrictStr] = Field(default=None, description="Content provider name.")
    adaptation_product_id: Optional[StrictInt] = Field(default=None, description="Adaptation product ID.")
    adaptation_vendor: Optional[StrictStr] = Field(default=None, description="Adaptation vendor name.")
    vendor_song_id: Optional[StrictStr] = Field(default=None, description="Vendor song ID.")
    commission_override_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Commission override rate as a decimal.")
    publisher_name: Optional[StrictStr] = Field(default=None, description="Publisher name.")
    medley_assets: Optional[List[MedleyAssetItem]] = Field(default=None, description="List of medley assets included in this user-generated content.")
    __properties: ClassVar[List[str]] = ["black_box", "arrangeable", "vendor_product_type", "seller_id", "authorized_performers", "content_provider", "adaptation_product_id", "adaptation_vendor", "vendor_song_id", "commission_override_rate", "publisher_name", "medley_assets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsergenItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in medley_assets (list)
        _items = []
        if self.medley_assets:
            for _item_medley_assets in self.medley_assets:
                if _item_medley_assets:
                    _items.append(_item_medley_assets.to_dict())
            _dict['medley_assets'] = _items
        # set to None if adaptation_product_id (nullable) is None
        # and model_fields_set contains the field
        if self.adaptation_product_id is None and "adaptation_product_id" in self.model_fields_set:
            _dict['adaptation_product_id'] = None

        # set to None if adaptation_vendor (nullable) is None
        # and model_fields_set contains the field
        if self.adaptation_vendor is None and "adaptation_vendor" in self.model_fields_set:
            _dict['adaptation_vendor'] = None

        # set to None if vendor_song_id (nullable) is None
        # and model_fields_set contains the field
        if self.vendor_song_id is None and "vendor_song_id" in self.model_fields_set:
            _dict['vendor_song_id'] = None

        # set to None if commission_override_rate (nullable) is None
        # and model_fields_set contains the field
        if self.commission_override_rate is None and "commission_override_rate" in self.model_fields_set:
            _dict['commission_override_rate'] = None

        # set to None if publisher_name (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_name is None and "publisher_name" in self.model_fields_set:
            _dict['publisher_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsergenItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "black_box": obj.get("black_box"),
            "arrangeable": obj.get("arrangeable"),
            "vendor_product_type": obj.get("vendor_product_type"),
            "seller_id": obj.get("seller_id"),
            "authorized_performers": obj.get("authorized_performers"),
            "content_provider": obj.get("content_provider"),
            "adaptation_product_id": obj.get("adaptation_product_id"),
            "adaptation_vendor": obj.get("adaptation_vendor"),
            "vendor_song_id": obj.get("vendor_song_id"),
            "commission_override_rate": obj.get("commission_override_rate"),
            "publisher_name": obj.get("publisher_name"),
            "medley_assets": [MedleyAssetItem.from_dict(_item) for _item in obj["medley_assets"]] if obj.get("medley_assets") is not None else None
        })
        return _obj


