# coding: utf-8

# flake8: noqa

"""
    HL Connect

    HL Connect provides a simplified API interface to Hal Leonard's Digital Asset Management (DAM) system. This API enables vendors to integrate with Hal Leonard's digital content distribution platform to purchase registrations, download, and manage digital sheet music and other media assets

    The version of the OpenAPI document: 0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "AssetsApi",
    "HealthApi",
    "PurchaseApi",
    "PurchaseCancelApi",
    "PurchaseDownloadUrlApi",
    "PurchaseInfoApi",
    "PurchaseRegisterApi",
    "PurchaseValidationApi",
    "PurchaseViewUrlApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AssetItem",
    "AssetPartForm",
    "AssetsListResponse",
    "ContributorItem",
    "DownloadUrl",
    "ErrorResponse",
    "HealthItem",
    "ImageItem",
    "InstrumentItem",
    "MedleyAssetItem",
    "OrderItem",
    "OrderProcessingFailedResponse",
    "PackageItem",
    "PriceItem",
    "PurchaseInProcessingResponse",
    "PurchaseRegisterRequest",
    "PurchaseValidateBeforePaymentRequest",
    "RelatedGoodItem",
    "RenderingItem",
    "UsergenItem",
    "ValidationToken",
    "ViewUrl",
]

# import apis into sdk package
from hlconnect_client.api.assets_api import AssetsApi as AssetsApi
from hlconnect_client.api.health_api import HealthApi as HealthApi
from hlconnect_client.api.purchase_api import PurchaseApi as PurchaseApi
from hlconnect_client.api.purchase_cancel_api import PurchaseCancelApi as PurchaseCancelApi
from hlconnect_client.api.purchase_download_url_api import PurchaseDownloadUrlApi as PurchaseDownloadUrlApi
from hlconnect_client.api.purchase_info_api import PurchaseInfoApi as PurchaseInfoApi
from hlconnect_client.api.purchase_register_api import PurchaseRegisterApi as PurchaseRegisterApi
from hlconnect_client.api.purchase_validation_api import PurchaseValidationApi as PurchaseValidationApi
from hlconnect_client.api.purchase_view_url_api import PurchaseViewUrlApi as PurchaseViewUrlApi

# import ApiClient
from hlconnect_client.api_response import ApiResponse as ApiResponse
from hlconnect_client.api_client import ApiClient as ApiClient
from hlconnect_client.configuration import Configuration as Configuration
from hlconnect_client.exceptions import OpenApiException as OpenApiException
from hlconnect_client.exceptions import ApiTypeError as ApiTypeError
from hlconnect_client.exceptions import ApiValueError as ApiValueError
from hlconnect_client.exceptions import ApiKeyError as ApiKeyError
from hlconnect_client.exceptions import ApiAttributeError as ApiAttributeError
from hlconnect_client.exceptions import ApiException as ApiException

# import models into sdk package
from hlconnect_client.models.asset_item import AssetItem as AssetItem
from hlconnect_client.models.asset_part_form import AssetPartForm as AssetPartForm
from hlconnect_client.models.assets_list_response import AssetsListResponse as AssetsListResponse
from hlconnect_client.models.contributor_item import ContributorItem as ContributorItem
from hlconnect_client.models.download_url import DownloadUrl as DownloadUrl
from hlconnect_client.models.error_response import ErrorResponse as ErrorResponse
from hlconnect_client.models.health_item import HealthItem as HealthItem
from hlconnect_client.models.image_item import ImageItem as ImageItem
from hlconnect_client.models.instrument_item import InstrumentItem as InstrumentItem
from hlconnect_client.models.medley_asset_item import MedleyAssetItem as MedleyAssetItem
from hlconnect_client.models.order_item import OrderItem as OrderItem
from hlconnect_client.models.order_processing_failed_response import OrderProcessingFailedResponse as OrderProcessingFailedResponse
from hlconnect_client.models.package_item import PackageItem as PackageItem
from hlconnect_client.models.price_item import PriceItem as PriceItem
from hlconnect_client.models.purchase_in_processing_response import PurchaseInProcessingResponse as PurchaseInProcessingResponse
from hlconnect_client.models.purchase_register_request import PurchaseRegisterRequest as PurchaseRegisterRequest
from hlconnect_client.models.purchase_validate_before_payment_request import PurchaseValidateBeforePaymentRequest as PurchaseValidateBeforePaymentRequest
from hlconnect_client.models.related_good_item import RelatedGoodItem as RelatedGoodItem
from hlconnect_client.models.rendering_item import RenderingItem as RenderingItem
from hlconnect_client.models.usergen_item import UsergenItem as UsergenItem
from hlconnect_client.models.validation_token import ValidationToken as ValidationToken
from hlconnect_client.models.view_url import ViewUrl as ViewUrl

